implemented get_B_max in a different way to find the max and not make…
MCFlowMace/CRESana pull request #8
Opened 2023-10-31 09:15 UTC by renereimann

… assumption that the max is at a coil position. Instead we first scan the range between all coils and get a guess for the maximum. Then we find the maximum by requireing dBz/dz = 0. At the position of the maximum we return the field value.

This should fix Issue #6 .

2023-10-31 14:44 UTC, MCFlowMace commented
It seems like this is returning the minimum instead of the maximum. Tried running it with [cresana_samples/run_coil_simulation.py](https://github.com/MCFlowMace/CRESana/blob/75a7803b408e3d38dabfa5295cf28818e0df6379/cresana_samples/run_coil_simulation.py)

2023-10-31 14:45 UTC, MCFlowMace requested changes
See comment

2023-11-02 12:56 UTC, renereimann commented
> It seems like this is returning the minimum instead of the maximum. Tried running it with [cresana_samples/run_coil_simulation.py](https://github.com/MCFlowMace/CRESana/blob/75a7803b408e3d38dabfa5295cf28818e0df6379/cresana_samples/run_coil_simulation.py)

The last commit addresses the issue. Tests show that the new implementation works and also for this example the maximum is returned.

2023-11-16 10:00 UTC, MCFlowMace approved these changes

2023-11-16 10:01 UTC, merged